name: localchain
description: tiki mobile blockchain
version: 0.0.2
homepage: https://mytiki.com
repository: https://github.com/tiki/localchain
issue_tracker: https://github.com/tiki/localchain/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  sqflite_sqlcipher: ^2.1.0
  pointycastle: ^3.5.0
  collection: ^1.15.0

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/localchain/src/db/sql/db_sql_create.sql
    - packages/localchain/src/db/sql/db_sql_update_v2.sql
