name: tiki_localchain
description: tiki mobile blockchain
version: 0.0.6
homepage: https://mytiki.com
repository: https://github.com/tiki/localchain
issue_tracker: https://github.com/tiki/localchain/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  sqflite_sqlcipher: ^2.1.1
  pointycastle: ^3.6.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/tiki_localchain/src/db/sql/db_sql_create.sql
    - packages/tiki_localchain/src/db/sql/db_sql_update_v2.sql
